kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service.kafka-dev.svc.cluster.local  #hostname for kakfa. Replace it, whatever!!!
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-server.kafka-dev.svc.cluster.local:2181 # can add service name instead of hostname of zookeeper
        - name: KAFKA_CREATE_TOPICS 
          value: mytopic:2:1    # example topic. you could remove that. just for test!!!
